# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

workspace 'CompanyDetails'

project 'CompanyDetails'
project 'CompanyDetailsExample/CompanyDetailsExample.xcodeproj'

def shared_pods
  pod 'TinkoffKit', :path => '../TinkoffKit'
  pod 'SwiftLint'
  pod 'Storage', :path => '../Storage'
  pod 'TinkoffNetwork', :path => '../TinkoffNetwork'
end

target 'CompanyDetails' do
  project 'CompanyDetails'
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  shared_pods
end

target 'CompanyDetailsExample' do
  project 'CompanyDetailsExample/CompanyDetailsExample.xcodeproj'
  use_frameworks!
  pod 'CompanyDetails', :path => '../CompanyDetails'
end