# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
def shared_pods
  pod 'TinkoffKit', :path => '../TinkoffKit'
end

target 'StockList' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for StockList
  shared_pods

  target 'StockListTests' do
    # Pods for testing
    shared_pods
  end

end
