# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

def shared
  pod 'SwiftLint'
  pod 'R.swift'
end

target 'TinkoffKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  shared

  target 'TinkoffKitTests' do
    shared
  end

end
