# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

def shared
  pod 'SwiftLint'
end

target 'TinkoffKit' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  shared

  target 'TinkoffKitTests' do
    shared
  end

end
